# Generated by Django 6.0.1 on 2026-01-15 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('csv_file', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='CSV файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('status', models.CharField(choices=[('uploaded', '📥 Загружен'), ('processing', '⚙️ В обработке'), ('completed', '✅ Обработан'), ('failed', '❌ Ошибка')], default='uploaded', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Датасет',
                'verbose_name_plural': 'Датасеты',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DataCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('missing', '🔍 Пропущенные значения'), ('duplicates', '♻️ Дубликаты строк'), ('statistics', '📊 Статистика')], max_length=20, verbose_name='Тип проверки')),
                ('result_json', models.JSONField(blank=True, default=dict, verbose_name='Результат (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='data_quality.dataset')),
            ],
            options={
                'verbose_name': 'Проверка данных',
                'verbose_name_plural': 'Проверки данных',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, verbose_name='Сводка')),
                ('issues_count', models.IntegerField(default=0, verbose_name='Количество проблем')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Сгенерирован')),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='data_quality.dataset')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
            },
        ),
    ]
